### ISSUE TITLE
jpeg <0.0.0a run constrain breaks pillow torchvision compatibility

### ISSUE THREAD

**Issue by junpuf** [conda-forge/libjpeg-turbo-feedstock#28]
### Comment:

Hi @hmaarrfk and all

There is an compatibility issue introduced between libjpeg-turbo 2.1.5.1 (via pillow 9.5.0) and any torchvison version due to the addition of `jpeg <0.0.0a` run constrain in https://github.com/conda-forge/libjpeg-turbo-feedstock/commit/6cee8324c6109060155cfe31c4175a62f7628eef. 

May i ask the rational of this breaking change in an update between `2.1.4` build 0 to `2.1.4` build 1?

Also, further investigation found that `jpeg <0.0.0a` doesn't map to any existing `jpeg` conda package versions in [conda-forge](https://anaconda.org/conda-forge/jpeg), which means this constrain will eliminate the compatibility between `libjpeg-turbo` and any other conda package that depend on `jpeg`.

```
The following packages are incompatible
├─ pillow 9.5.0**  is installable and it requires
│  └─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which requires
│     └─ jpeg <0.0.0a , which can be installed;
└─ torchvision   is uninstallable because there are no viable options
   ├─ torchvision [0.15.1|0.15.2] would require
   │  └─ jpeg  , which conflicts with any installable versions previously reported;
   └─ torchvision [0.10.0|0.10.1|...|0.9.1] conflicts with any installable versions previously reported.
```

Reference:
- Pillow's update on libjpeg-turbo https://github.com/python-pillow/Pillow/pull/6929

**Comment by hmaarrfk** [comment]
Please see https://github.com/conda-forge/conda-forge.github.io/issues/673 

The last comment is me mostly admitting the difficulty in fixing the problem you are hitting.

My solution has been to

```
conda uninstall --force --offline --yes jpeg
mamba update --all --yes
```
generally gets you through.

https://github.com/conda-forge/conda-forge.github.io/issues/1894

**Comment by hmaarrfk** [comment]
> software maintainers

As I understand it torchvision, the recipe you linked to, is not dependent on the conda-forge ecosystem.
https://github.com/pytorch/vision/blob/main/packaging/torchvision/conda_build_config.yaml#L2

while there used to be a big alignment between `defaults` and `conda-forge` in the past, the two channels are, today, largely incompatible.

The torchvision package from conda-forge should be compatible 
https://github.com/conda-forge/torchvision-feedstock/

on windows, we could use help in the form of packing, or donation of your "time" to manually build windows from time to time.

see the many attempts at building windows:
https://github.com/conda-forge/pytorch-cpu-feedstock/pulls

**Comment by hmaarrfk** [comment]
I forgot to say, thank you for being so understanding of the tradeoffs.

**Comment by janxkoci** [comment]
I run into this while preparing my environment for a package I need to install from github. The following command gives me an error:

```bash
$ mamba create -n slendr091 r-pak r-remotes pkg-config r-irkernel jupyter_console r-tidyverse r-reticulate r-png r-shiny r-igraph r::r-ijtiff        

Looking for: ['r-pak', 'r-remotes', 'pkg-config', 'r-irkernel', 'jupyter_console', 'r-tidyverse', 'r-reticulate', 'r-png', 'r-shiny', 'r-igraph', 'r::r-ijtiff']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
r/linux-64                                                  Using cache
r/noarch                                                    Using cache
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following package could not be installed
└─ r-ijtiff is not installable because it requires
   ├─ jpeg >=9e,<10a , which can be installed;
   └─ r-base >=4.3,<4.4.0a0  but there are no viable options
      ├─ r-base [4.3.0|4.3.1|4.3.2|4.3.3] would require
      │  └─ libjpeg-turbo [>=2.1.5.1,<3.0a0 |>=3.0.0,<4.0a0 ], which requires
      │     └─ jpeg <0.0.0a , which conflicts with any installable versions previously reported;
      └─ r-base 4.3.1 conflicts with any installable versions previously reported.
```

From the error I see that `libjpeg-turbo` itself depends on `jpeg` - how am I supposed to resolve that? Switching to `libjpeg-turbo` is clearly not gonna work, if it depends on `jpeg` like this.

**Comment by hmaarrfk** [comment]
R ijtiff should be recompiled for jpegturbo. 

This isn’t a conda-forge problem. 

Happy to comment if you create an issue on the r ijtiff issue tracker and then cross reference it.
